### PR TITLE
Add Gemfile with rake and SimpleCov dependencies

### PR DESCRIPTION
**Pull request by DanielEFrampton**
Co-Authored-By: Phil DeLong <philjdelong@users.noreply.github.com>
Co-Authored-By: Ray <itemniner@users.noreply.github.com>
Co-Authored-By: Sebastian Sloan <sasloan@users.noreply.github.com>

### CODE REVIEW

**Comment by raymondknguyen** [comment]
PERFECT!

**Review by ghost — APPROVED** [review]
Looks gourgous darling

**Review by raymondknguyen — COMMENTED** [review]
thumbs up!

**Review by philjdelong — APPROVED** [review]
Approve.

**Review by raymondknguyen — APPROVED** [review]

**Pull request merged**
